"""
simulation.py — SDE simulation and model-based diagnostics

The fitted Student Kramers model is

    dX_t = V_t dt
    dV_t = [-eta V_t + F(X_t)] dt + sqrt(q(V_t)) dW_t,

where

    F(x) = a x^3 + b x^2 + c x + d,
    q(x,v) = alpha v^2 + beta v + gamma
             + delta x^2 + epsilon x v + zeta x.

Paths are generated by Euler--Maruyama at ``h_sim`` and retained every
``h_obs / h_sim`` steps.  The same simulator supports parametric bootstrap,
waiting-time analysis, first-passage analysis, and model checking.
"""
import numpy as np
import pandas as pd

from . import config
from .data_loading import build_partial_data
from .models import diffusion_rectangle_bounds, diffusion_variance, velocity_drift


def simulate_trajectory(params, n_obs, h_obs=config.H_OBS, h_sim=config.H_SIM,
                        init_state=(0.0, 0.0), seed=42):
    """
    Simulate one path and return an ``(n_obs, 2)`` array ``[X_t, V_t]``.

    Euler--Maruyama update:

        X_{n+1} = X_n + V_n h
        V_{n+1} = V_n + [-eta V_n + F(X_n)] h + sqrt(q(X_n,V_n) h) Z_n.
    """
    params = np.asarray(params, dtype=float)
    substeps = int(round(h_obs/h_sim))
    if substeps < 1 or not np.isclose(substeps*h_sim, h_obs):
        raise ValueError("h_obs must be an integer multiple of h_sim")

    rng = np.random.default_rng(seed)
    x, v = map(float, init_state)
    out = np.empty((n_obs, 2), dtype=float)
    out[0] = [x, v]
    sqrt_h = np.sqrt(h_sim)

    for i in range(1, n_obs):
        for _ in range(substeps):
            sigma2 = float(diffusion_variance(x, v, params))
            if not np.isfinite(sigma2) or sigma2 <= 0.0:
                raise FloatingPointError(
                    f"Diffusion variance became invalid at observation {i}: q={sigma2}"
                )
            x_new = x + v*h_sim
            v_new = (
                v + float(velocity_drift(x, v, params))*h_sim
                + np.sqrt(sigma2)*sqrt_h*rng.normal()
            )
            if not (np.isfinite(x_new) and np.isfinite(v_new)):
                raise FloatingPointError("Simulation produced non-finite values")
            if max(abs(x_new), abs(v_new)) > 1e6:
                raise FloatingPointError("Simulation exploded")
            x, v = x_new, v_new
        out[i] = [x, v]
    return out


def simulate_x(params, n_obs, h_obs=config.H_OBS, h_sim=config.H_SIM,
               init_state=(0.0, 0.0), seed=42):
    """Simulate and retain only the observed X component."""
    return simulate_trajectory(params, n_obs, h_obs, h_sim, init_state, seed)[:, 0]


def simulate_partial_data(params, n_obs, h_obs=config.H_OBS, h_sim=config.H_SIM,
                          init_state=(0.0, 0.0), seed=42):
    """Simulate X and reconstruct the pseudo-state data used by the likelihood."""
    return build_partial_data(simulate_x(params, n_obs, h_obs, h_sim, init_state, seed), h_obs)


def potential_extrema(params):
    """Return lower well, central barrier, and upper well when all exist."""
    _, a, b, c, d = np.asarray(params, dtype=float)[:5]
    roots = np.roots([a, b, c, d])
    real = np.sort(roots.real[np.abs(roots.imag) < 1e-8])
    if len(real) != 3:
        return np.nan, np.nan, np.nan
    slopes = 3.0*a*real**2 + 2.0*b*real + c
    if not (slopes[0] < 0.0 and slopes[1] > 0.0 and slopes[2] < 0.0):
        return np.nan, np.nan, np.nan
    return tuple(float(value) for value in real)


def compute_derived_params(params):
    """
    Return interpretable quantities for a symmetric double-well model.

    For ``F(x) = a*x^3 + c*x`` with ``a < 0`` and ``c > 0``:

        x_well = sqrt(-c/a),        Delta_U = c^2 / (4*(-a)).

    For M4, the minimum of q is computed over both x and v.  The returned
    minimizer is the minimum-norm solution when the quadratic form is
    singular, as it is for M1-M3.
    """
    from .models import diffusion_minimum, potential

    params = np.asarray(params, dtype=float)
    eta, a, b, c, d, alpha = params[:6]
    symmetric = np.isclose(b, 0.0) and np.isclose(d, 0.0)
    lower_well, barrier, upper_well = potential_extrema(params)
    minimizer, q_min = diffusion_minimum(params)
    return {
        "x_well": np.sqrt(-c/a) if symmetric and a < 0.0 and c > 0.0 else np.nan,
        "Delta_U": c**2/(4.0*(-a)) if symmetric and a < 0.0 else np.nan,
        "lower_well": lower_well,
        "barrier": barrier,
        "upper_well": upper_well,
        "Delta_U_lower": (
            float(potential(barrier, params) - potential(lower_well, params))
            if np.isfinite(barrier) else np.nan
        ),
        "Delta_U_upper": (
            float(potential(barrier, params) - potential(upper_well, params))
            if np.isfinite(barrier) else np.nan
        ),
        "q_min_x": float(minimizer[0]),
        "q_min_v": float(minimizer[1]),
        "mu_v": float(minimizer[1]),
        "q_min": q_min,
        "nu_proxy": 2.0*eta/alpha + 1.0 if alpha > 0.0 else np.inf,
    }


def classify_regime(x, barrier=0.0):
    """Classify each observation below/above the central barrier as -1/+1."""
    x = np.asarray(x, dtype=float)
    states = np.sign(x - barrier).astype(int)
    nonzero = np.flatnonzero(states != 0)
    if len(nonzero) == 0:
        return np.array([], dtype=int)
    states[:nonzero[0]] = states[nonzero[0]]
    for i in range(nonzero[0] + 1, len(states)):
        if states[i] == 0:
            states[i] = states[i - 1]
    return states


def extract_waiting_times(x, h=config.H_OBS, barrier=0.0):
    """Convert consecutive lower/upper regime runs into waiting times in years."""
    states = classify_regime(x, barrier)
    waits = {"lower": [], "upper": []}
    if len(states) == 0:
        return {key: np.array([], dtype=float) for key in waits}

    current, run_length = states[0], 1
    for state in states[1:]:
        if state == current:
            run_length += 1
        else:
            waits["lower" if current < 0 else "upper"].append(run_length*h*1000.0)
            current, run_length = state, 1
    waits["lower" if current < 0 else "upper"].append(run_length*h*1000.0)
    return {key: np.asarray(value, dtype=float) for key, value in waits.items()}


def summarize_waiting_times(waits, source):
    """Return counts, means, medians, and 95% intervals for each regime."""
    rows = []
    for regime, values in waits.items():
        rows.append({
            "source": source,
            "regime": regime,
            "n": len(values),
            "mean_years": np.mean(values) if len(values) else np.nan,
            "median_years": np.median(values) if len(values) else np.nan,
            "q025_years": np.quantile(values, 0.025) if len(values) else np.nan,
            "q975_years": np.quantile(values, 0.975) if len(values) else np.nan,
        })
    return pd.DataFrame(rows)


def simulate_waiting_times(params, n_obs, n_rep, init_state, seed=42,
                           h_obs=config.H_OBS, h_sim=config.H_SIM, barrier=0.0):
    """Simulate independent paths and pool their lower/upper waiting times."""
    pooled = {"lower": [], "upper": []}
    for rep in range(n_rep):
        x = simulate_x(params, n_obs, h_obs, h_sim, init_state, seed + rep)
        waits = extract_waiting_times(x, h_obs, barrier)
        for key in pooled:
            pooled[key].extend(waits[key])
    return {key: np.asarray(value, dtype=float) for key, value in pooled.items()}


def simulate_first_passage(params, start_x, barrier=0.0, n_paths=1000,
                           h_sim=config.H_SIM, t_max=100.0, seed=42):
    """Simulate first hitting times from ``start_x`` to the central barrier."""
    rng = np.random.default_rng(seed)
    max_steps = int(t_max/h_sim)
    times = np.full(n_paths, np.nan)
    for path in range(n_paths):
        x, v = float(start_x), 0.0
        direction = 1.0 if start_x < barrier else -1.0
        for step in range(1, max_steps + 1):
            sigma2 = float(diffusion_variance(x, v, params))
            if not np.isfinite(sigma2) or sigma2 <= 0.0:
                raise FloatingPointError(f"Diffusion variance became invalid: q={sigma2}")
            x_new = x + v*h_sim
            v_new = (
                v + float(velocity_drift(x, v, params))*h_sim
                + np.sqrt(sigma2*h_sim)*rng.normal()
            )
            x, v = x_new, v_new
            if direction*(x - barrier) >= 0.0:
                times[path] = step*h_sim
                break
    return times


def path_summary_matrix(X_paths, Vhat_paths):
    """Return one row of marginal model-check statistics per simulated path."""
    def block(A, prefix):
        return pd.DataFrame({
            f"{prefix}_mean": np.mean(A, axis=1),
            f"{prefix}_sd": np.std(A, axis=1, ddof=1),
            f"{prefix}_q05": np.quantile(A, 0.05, axis=1),
            f"{prefix}_q50": np.quantile(A, 0.50, axis=1),
            f"{prefix}_q95": np.quantile(A, 0.95, axis=1),
        })
    return pd.concat([block(X_paths, "X"), block(Vhat_paths, "Vhat")], axis=1)


def observed_summary(x, vhat):
    """Return the observed counterpart of ``path_summary_matrix``."""
    return pd.Series({
        "X_mean": np.mean(x), "X_sd": np.std(x, ddof=1),
        "X_q05": np.quantile(x, 0.05), "X_q50": np.quantile(x, 0.50),
        "X_q95": np.quantile(x, 0.95), "Vhat_mean": np.mean(vhat),
        "Vhat_sd": np.std(vhat, ddof=1), "Vhat_q05": np.quantile(vhat, 0.05),
        "Vhat_q50": np.quantile(vhat, 0.50), "Vhat_q95": np.quantile(vhat, 0.95),
    })


def simulate_model_check(params, n_obs, n_rep, init_state, seed=42):
    """Return simulated X and reconstructed-velocity arrays for model checking."""
    X, Vhat = [], []
    for rep in range(n_rep):
        traj = simulate_trajectory(params, n_obs, init_state=init_state, seed=seed + rep)
        x = traj[:, 0]
        X.append(x[:-1])
        Vhat.append(np.diff(x)/config.H_OBS)
    return np.asarray(X), np.asarray(Vhat)


def simulate_diffusion_check(params, data, n_rep=100, seed=42,
                             h_obs=config.H_OBS, h_sim=config.H_SIM):
    """
    Check M4 diffusion positivity on simulated paths at the fitted-data scale.

    Each row records whether simulation succeeded, the minimum q on the true
    simulated states and reconstructed partial states, and the fraction of
    reconstructed states outside the protected real-data rectangle.
    """
    data = np.asarray(data, dtype=float)
    lo, hi = diffusion_rectangle_bounds(data, config.M4_DIAGNOSTIC_MARGIN)
    rows = []
    for rep in range(n_rep):
        row = {"rep": rep, "success": False}
        try:
            traj = simulate_trajectory(
                params, len(data) + 1, h_obs, h_sim,
                init_state=tuple(data[0]), seed=seed + rep,
            )
            partial = build_partial_data(traj[:, 0], h_obs)
            q_true = diffusion_variance(traj[:, 0], traj[:, 1], params)
            q_partial = diffusion_variance(partial[:, 0], partial[:, 1], params)
            outside = np.any((partial < lo) | (partial > hi), axis=1)
            row.update({
                "success": True,
                "q_min_true": float(np.min(q_true)),
                "q_min_partial": float(np.min(q_partial)),
                "outside_fraction": float(np.mean(outside)),
                "max_abs_x": float(np.max(np.abs(traj[:, 0]))),
                "max_abs_v": float(np.max(np.abs(traj[:, 1]))),
            })
        except (FloatingPointError, OverflowError, ValueError):
            row.update({
                "q_min_true": np.nan,
                "q_min_partial": np.nan,
                "outside_fraction": np.nan,
                "max_abs_x": np.nan,
                "max_abs_v": np.nan,
            })
        rows.append(row)
    return pd.DataFrame(rows)
